block_newline_gaps = "Preserve"
call_parentheses = "Always"
collapse_simple_statement = "Never"
column_width = 80
indent_type = "Spaces"
indent_width = 4
line_endings = "Unix"
quote_style = "ForceDouble"
space_after_function_names = "Never"

[sort_requires]
enabled = false
